name: Build and Push Docker Image

on:
  push:
    branches:
      - main   # trigger only on main branch

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: 
      contents: read
      packages: write

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Login to Registry
      - name: Log in to Registry
        uses: docker/login-action@v3
        with:
          registry: https://docker-hosted.dapa.ir:8084/
          username: admin
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build Docker image
      - name: Build image
        run: |
          docker build -f docker/Dockerfile -t docker-hosted.dapa.ir:8084/myapp:latest .

      # 4. Push Docker image
      - name: Push image
        run: |
          docker push docker-hosted.dapa.ir:8084/myapp:latest
